### ISSUE TITLE
SANDBOX

### ISSUE THREAD

**Issue by esther-poniatowski** [esther-poniatowski/multitask-context-dependent-behavior#47]
# Tasks
- [ ] Create a note for the method to use git with branches, commits, staging and stashing
- [ ] Clearn the repository history
- [ ] Are there tools to compare changes ?
- [ ] Are there tools to review before merging ?
- [ ] Use git -p
- [ ] How to create issues from code directly ?
- [ ] How to create issues from draft ?
- [ ] Test Data class with raw firing rates
