### ISSUE TITLE
New Analyses

### ISSUE THREAD

**Issue by esther-poniatowski** [esther-poniatowski/multitask-context-dependent-behavior#52]

**Comment by esther-poniatowski** [comment]
### Tasks
- [ ] Control for Drift : Within task and Across tasks (split trials according to time).
- [ ] Tonic encoding of the task during stimulus processing ? Compare responses to TORC in tasks PTD and CLK.
- [ ] Control Motor related activity : Licking behavior not possible during passive. Check whether there is a difference in lick histogram across tasks.
