### ISSUE TITLE
Code Maintenance

### ISSUE THREAD

**Issue by esther-poniatowski** [esther-poniatowski/multitask-context-dependent-behavior#53]
### Tasks

- [ ] Rename MetaData to AttributeEnforcer : [MetaData](https://github.com/esther-poniatowski/multitask-context-dependent-behavior/blob/c291477dcf58df3cb64c5594b485f50e3a8a4d93/src/mtcdb/data_structures/base.py#L78)
- [ ] Update documentation
- [ ] Reformat tests to use fixtures
- [ ] Clear the repository history
- [ ] Keep trace of pipelines used to generate data: either in YAML file in the output directory, or attribute in data themselves.

**Comment by esther-poniatowski** [comment]
### Tasks
- [ ] Update documentation
- [ ] Reformat tests to use fixtures
