### ISSUE TITLE
[Issue] - Hierarchical Bootstrap

### ISSUE THREAD

**Issue by esther-poniatowski** [esther-poniatowski/multitask-context-dependent-behavior#55]
### Goal

Implement the method for pairing the trials of the units.

### Acceptance Criteria

- [x] Take as input the counts of trials for all units.
- [x] Determine the number of pseudo-trials to generate.
- [x] Return the array of shape `(nunits, ntrials)` which contains the indices of all the trials to pair.

### Tasks

- [ ]

### Dependencies

- Related to #48 (parent)

### Cross-References

- [Branch](https://github.com/esther-poniatowski/multitask-context-dependent-behavior/tree/hierarchical-bootstrap)
