### ISSUE TITLE
[Issue] - Load data

### ISSUE THREAD

**Issue by esther-poniatowski** [esther-poniatowski/multitask-context-dependent-behavior#56]
### Goal

Be able to manipulate data from single neurons.

### Acceptance Criteria

- [x] Get data from one neuron in a single instantiation, such as : `data = RawData(unit, session)`

### Tasks

- [x] Finish Data Class
- [x] Implement RawData class
- [x] Load raw data

### Dependencies

- Related to #48 

### Cross-References

- [Module](https://github.com/esther-poniatowski/multitask-context-dependent-behavior/tree/main/src/mtcdb/data_structures)
